mongo: # mongo atlas db : main thinga
  type: "uniqueURL"
  url: "mongodb://M0ngoloid€@cluster0-shard-00-00-q3mln.mongodb.net:27017,cluster0-shard-00-01-q3mln.mongodb.net:27017,cluster0-shard-00-02-q3mln.mongodb.net:27017/unrealmart?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin"
  database: "unrealmart"
mysql: #digital ocean db: logs, location of remote bu 
  type: "credentials" 
  host: "46.101.238.71",
  user: "root",
  password: "massaciuccoli"
  database: "unrealmart_bis"